# Snowflake Configuration
snowflake.url=jdbc:snowflake://GEWIWIQ-YU40228.snowflakecomputing.com/?warehouse=COMPUTE_WH&db=MEDICAL_QUIZ&schema=PUBLIC&query_result_format-json
snowflake.user=JaneDoe123
snowflake.password=Quiztesting123
spring.datasource.driver-class-name=net.snowflake.client.jdbc.SnowflakeDriver

# Force JSON format (critical!)
spring.datasource.hikari.data-source-properties.query_result_format=json

# Server
server.address=0.0.0.0
server.port=8080
app.public-url=